LIBS:
  CRAN:
    - tidyverse
    - tidytext
    - janeaustenr
    - gutenbergr
    - scales
    - wordcloud
    - ggraph
    - widyr
    - igraph
    - rlang
    - tm
    - topicmodels
    - quanteda
    - methods
    - Matrix
    - tm.plugin.webmining


